[apirambo] This instead fails - and is what I needed
In file included from MemoryAccessMomenta.h:8,
                 from RamboSamplingKernels.cc:4:
MemoryAccessBase.h: In instantiation of ‘constexpr double& (* const MemoryAccessBase<MemoryAccessMomentaBase>::ieventAccessFIELD2)(double*, int, int, int)’:
MemoryAccessBase.h:61:56:   required from ‘static mgOnGpu::fptype& MemoryAccessBase<T>::ieventAccessField(mgOnGpu::fptype*, int, int, int) [with T = MemoryAccessMomentaBase; mgOnGpu::fptype = double]’
MemoryAccessMomenta.h:67:90:   required from here
MemoryAccessBase.h:51:25: error: no matches converting function ‘ieventAccessFIELD’ to type ‘double& (* const)(double*, int, int, int)’
   51 |   static constexpr auto ieventAccessFIELD2 = ieventAccessFIELD<const int, const int>; // builds or not builds depending on below
      |                         ^~~~~~~~~~~~~~~~~~
MemoryAccessBase.h:42:11: note: candidate is: ‘template<class ... Ts> static mgOnGpu::fptype& MemoryAccessBase<T>::ieventAccessFIELD(mgOnGpu::fptype*, int, Ts ...) [with Ts = {Ts ...}; T = MemoryAccessMomentaBase]’
   42 |   fptype& ieventAccessFIELD( fptype* buffer,
      |           ^~~~~~~~~~~~~~~~~
make: *** [RamboSamplingKernels.o] Error 1